const currencies = [
  { code: "AED", country: "United Arab Emirates" },
  { code: "AFN", country: "Afghanistan" },
  { code: "XCD", country: "East Caribbean" },
  { code: "ALL", country: "Albania" },
  { code: "AMD", country: "Armenia" },
  { code: "ANG", country: "Netherlands Antilles" },
  { code: "AOA", country: "Angola" },
  { code: "AQD", country: "Antarctica" },
  { code: "ARS", country: "Argentina" },
  { code: "AUD", country: "Australia" },
  { code: "AZN", country: "Azerbaijan" },
  { code: "BAM", country: "Bosnia and Herzegovina" },
  { code: "BBD", country: "Barbados" },
  { code: "BDT", country: "Bangladesh" },
  { code: "XOF", country: "West African CFA" },
  { code: "BGN", country: "Bulgaria" },
  { code: "BHD", country: "Bahrain" },
  { code: "BIF", country: "Burundi" },
  { code: "BMD", country: "Bermuda" },
  { code: "BND", country: "Brunei" },
  { code: "BOB", country: "Bolivia" },
  { code: "BRL", country: "Brazil" },
  { code: "BSD", country: "Bahamas" },
  { code: "NOK", country: "Norway" },
  { code: "BWP", country: "Botswana" },
  { code: "BYR", country: "Belarus" },
  { code: "BZD", country: "Belize" },
  { code: "CAD", country: "Canada" },
  { code: "CDF", country: "DR Congo" },
  { code: "XAF", country: "Central African CFA" },
  { code: "CHF", country: "Switzerland" },
  { code: "CLP", country: "Chile" },
  { code: "CNY", country: "China" },
  { code: "COP", country: "Colombia" },
  { code: "CRC", country: "Costa Rica" },
  { code: "CUP", country: "Cuba" },
  { code: "CVE", country: "Cape Verde" },
  { code: "CYP", country: "Cyprus" },
  { code: "CZK", country: "Czech Republic" },
  { code: "DJF", country: "Djibouti" },
  { code: "DKK", country: "Denmark" },
  { code: "DOP", country: "Dominican Republic" },
  { code: "DZD", country: "Algeria" },
  { code: "EGP", country: "Egypt" },
  { code: "ETB", country: "Ethiopia" },
  { code: "EUR", country: "European Union" },
  { code: "FJD", country: "Fiji" },
  { code: "FKP", country: "Falkland Islands" },
  { code: "GBP", country: "United Kingdom" },
  { code: "GEL", country: "Georgia" },
  { code: "GHS", country: "Ghana" },
  { code: "GIP", country: "Gibraltar" },
  { code: "GMD", country: "Gambia" },
  { code: "GNF", country: "Guinea" },
  { code: "GTQ", country: "Guatemala" },
  { code: "GYD", country: "Guyana" },
  { code: "HKD", country: "Hong Kong" },
  { code: "HNL", country: "Honduras" },
  { code: "HRK", country: "Croatia" },
  { code: "HTG", country: "Haiti" },
  { code: "HUF", country: "Hungary" },
  { code: "IDR", country: "Indonesia" },
  { code: "ILS", country: "Israel" },
  { code: "INR", country: "India" },
  { code: "IQD", country: "Iraq" },
  { code: "IRR", country: "Iran" },
  { code: "ISK", country: "Iceland" },
  { code: "JMD", country: "Jamaica" },
  { code: "JOD", country: "Jordan" },
  { code: "JPY", country: "Japan" },
  { code: "KES", country: "Kenya" },
  { code: "KRW", country: "South Korea" },
  { code: "KWD", country: "Kuwait" },
  { code: "KZT", country: "Kazakhstan" },
  { code: "LKR", country: "Sri Lanka" },
  { code: "MAD", country: "Morocco" },
  { code: "MXN", country: "Mexico" },
  { code: "MYR", country: "Malaysia" },
  { code: "NGN", country: "Nigeria" },
  { code: "NPR", country: "Nepal" },
  { code: "NZD", country: "New Zealand" },
  { code: "OMR", country: "Oman" },
  { code: "PHP", country: "Philippines" },
  { code: "PKR", country: "Pakistan" },
  { code: "PLN", country: "Poland" },
  { code: "QAR", country: "Qatar" },
  { code: "RON", country: "Romania" },
  { code: "RUB", country: "Russia" },
  { code: "SAR", country: "Saudi Arabia" },
  { code: "SEK", country: "Sweden" },
  { code: "SGD", country: "Singapore" },
  { code: "THB", country: "Thailand" },
  { code: "TRY", country: "Turkey" },
  { code: "TWD", country: "Taiwan" },
  { code: "UAH", country: "Ukraine" },
  { code: "UGX", country: "Uganda" },
  { code: "USD", country: "United States" },
  { code: "UYU", country: "Uruguay" },
  { code: "VND", country: "Vietnam" },
  { code: "YER", country: "Yemen" },
  { code: "ZAR", country: "South Africa" }
];

const fromSelect = document.getElementById("from");
const toSelect = document.getElementById("to");

currencies.forEach(currency => {
  const option1 = document.createElement("option");
  option1.value = currency.code;
  option1.textContent = `${currency.country} (${currency.code})`;
  fromSelect.appendChild(option1);

  const option2 = option1.cloneNode(true);
  toSelect.appendChild(option2);
});

fromSelect.value = "USD";
toSelect.value = "INR";
